version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-local
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_BASICAUTH=false

volumes:
  mongo-data: